# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "scide"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Simon Oulevay (AlphaHydrae)"]
  s.date = "2013-05-02"
  s.description = "GNU screen wrapper to open projects with a .screenrc file."
  s.email = "hydrae.alpha@gmail.com"
  s.executables = ["scide"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".ruby-version",
    ".screenrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/scide",
    "lib/scide.rb",
    "lib/scide/auto.rb",
    "lib/scide/list.rb",
    "lib/scide/open.rb",
    "lib/scide/program.rb",
    "lib/scide/setup.rb",
    "scide.gemspec",
    "spec/auto_spec.rb",
    "spec/cli/list_spec.rb",
    "spec/cli/open_spec.rb",
    "spec/cli/setup_spec.rb",
    "spec/helper.rb",
    "spec/list_spec.rb",
    "spec/open_spec.rb",
    "spec/setup_spec.rb",
    "spec/version_spec.rb"
  ]
  s.homepage = "http://github.com/AlphaHydrae/scide"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "GNU Screen IDE"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<commander>, ["~> 4.1.3"])
      s.add_runtime_dependency(%q<paint>, ["~> 0.8.6"])
      s.add_runtime_dependency(%q<which_works>, ["~> 1.0.0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<fakefs>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<gemcutter>, [">= 0"])
      s.add_development_dependency(%q<gem-release>, [">= 0"])
      s.add_development_dependency(%q<rake-version>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<travis-lint>, [">= 0"])
    else
      s.add_dependency(%q<commander>, ["~> 4.1.3"])
      s.add_dependency(%q<paint>, ["~> 0.8.6"])
      s.add_dependency(%q<which_works>, ["~> 1.0.0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<fakefs>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<gemcutter>, [">= 0"])
      s.add_dependency(%q<gem-release>, [">= 0"])
      s.add_dependency(%q<rake-version>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<travis-lint>, [">= 0"])
    end
  else
    s.add_dependency(%q<commander>, ["~> 4.1.3"])
    s.add_dependency(%q<paint>, ["~> 0.8.6"])
    s.add_dependency(%q<which_works>, ["~> 1.0.0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<fakefs>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<gemcutter>, [">= 0"])
    s.add_dependency(%q<gem-release>, [">= 0"])
    s.add_dependency(%q<rake-version>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<travis-lint>, [">= 0"])
  end
end

