#!/usr/bin/env bash
set -e

cleanup() {
  local tmp_file="$1"
  test -n "$tmp_file" && test -f "$tmp_file" && rm -f "$tmp_file"
}

fail() {
  >&2 echo "$@"
  exit 1
}

tmp_file=`mktemp -t scide.tests.XXX`
trap "cleanup $tmp_file" EXIT

bin_dir="${PWD}/bin"
mocks_dir="${PWD}/tests/mocks"
screen_mock="${mocks_dir}/screen"

test -d "$mocks_dir" && test -x "$screen_mock" \
  || fail "Could not find screen mock; make sure to execute the tests from the root of the repository"

PATH="$bin_dir:$mocks_dir:$PATH" \
  SCREEN_MOCK_DATA_FILE="$tmp_file" \
  ./tests/suite.sh
