#!/usr/bin/env bash
set -e

function fail() {
  >&2 echo "$@"
  exit 1
}

function watch() {
  local func="$1"
  local checksum1=""

  while [[ true ]]; do
    local checksum2=`find bin/ scripts/ tests/ -type f -exec md5sum {} \;`
    if [[ "$checksum1" != "$checksum2" ]]; then
      $func
      checksum1="$checksum2"
    fi
    sleep 2
  done
}

watch=

POSITIONAL=()
while [[ "$#" -gt 0 ]]; do
  key="$1"
  shift

  case "$key" in
    -w|--watch)
      watch=true
    ;;
    *)
      POSITIONAL+=("$1")
      shift
    ;;
  esac
done

# Restore positional parameters.
set -- "${POSITIONAL[@]}"

mocks_dir="${PWD}/tests/mocks"
screen_mock="${mocks_dir}/screen"
test -d "$mocks_dir" && test -x "$screen_mock" \
  || fail "Could not find screen mock; make sure to execute the tests from the root of the repository"

function run_tests() {
  bats -j "$(nproc --all)" ./tests/
}

test -n "$watch" && watch "run_tests" || run_tests
